### ISSUE TITLE
Follow up with CAIA on some outstanding questions

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#101]
These include:

- Application/Form/Request language standards
- Double checking implementation of suggestions
- Research findings around the process of changing name/dob/ssn

ACs
- [x] #95 has been closed
- [x] Follow up questions are put into the CAIA ticket
- [x] Next CAIA ticket draft includes request further clarification for the Application/Form/Request language standards
- [x]  Next CAIA ticket draft includes an item to go over previous changes to ensure we are on the same page as we go into Update Prefill pattern testing

**Comment by ChristineRoseSteiffer** [comment]
@msbtterswrth I did end up adding one more ticket for next sprint for our follow up questions to CAIA. This ticket has a dependency on #95 but I'm not sure how to create or indicate that in GH. Could you please help me with that?

**Comment by msbtterswrth** [comment]
I added this task to the BLOCKED column on our board and mentioned this task in it's blocking task. I've also added an AC for #95 to be completed as well.

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer @msbtterswrth Can someone update the AC's or description to better reflect the work done on this ticket? It seems like this ticket originally encompassed more than just content around updating uneditable information. 

For example, did we get confirmation on **Application/Form/Request language standards**?

**Comment by ChristineRoseSteiffer** [comment]
@beckyphung I have updated the AC's to better reflect what was done for this ticket. I have a draft ticket started for our next CAIA request that I will get submitted by the end of this week to work with them on Update Prefill as we're getting our next study going. I will include those two points in our ticket. Thanks!

**Comment by beckyphung** [comment]
Thanks @ChristineRoseSteiffer for updating the ticket. Closing now. I'll accept this as part of the previous sprint (Sprint 7).
