### ISSUE TITLE
AEDP Sprint #8 - Sept 25

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#108]
### Sprint Goal
We have conducted our USWDS workshop and have a solid understanding of our next pattern's research plan and design.

### Sprint Priorities

**Review Prefill**
- [x] #106 
- [x] #78 
- [x] #69 
- [x] #113
- [x] #116
- [x] #120 
- [x] #119 

**Update Prefill**
- [ ] #49 
- [x] #59 
- [x] #104 
- [ ] #115 (stretch)
    - [x] #114
    - [x] #117

**General Tasks**
- [x] #121
- [x] #122 
- [x] #125 (added)

### Team Capacity
Belle - OOO half Friday Oct 4
Adam - OOO Friday Oct 4
Kristen - OOO Monday Oct 7- Tuesday Oct 8

### Completed Items from last sprint
- [x] #68
- [x] #71 
- [x] #101
- [x] #109
- [x] #49 
    - [x] #103
    - [x] #105
    - [x] #111
- [x] #60 [stretch]
- [x] #74
- [x] #110

**Comment by beckyphung** [comment]
I added comments to #113 and #120 @msbtterswrth

**Comment by beckyphung** [comment]
Thanks for replying. This is good to close when you're ready. @msbtterswrth
