### ISSUE TITLE
[SPIKE] investigate non-dev starting codespaces

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#110]
Summary:

As an engineer, I would like a way to make applications in codespaces public easily and avoid having to require designers and researchers to operate the terminal and set up an automated process for making these codespaces run automatically.

Tasks:

- investigate getting an automated process added to set a codespace up from a branch with the mock server and fe dev server running when the codespace is created/started up.
- ensure that a codespace is only public when the user has opted in. This could be done via environment variables, client secret or some other configuration that is used as an on/off switch
- expose the dev servers to public ingress traffic automatically
- make this setup as easy as possible, but also flexible enough that it can be used outside of the authed-patterns team

AC:

- [x] codespace automated process created
- [x] configuration reviewed with team and demoed
- [x] PR for changes merged to main

**Comment by adamwhitlock1** [comment]
This is ready for internal review. @ChristineRoseSteiffer maybe we can meet soon to review it from the designer and researcher perspective to see if this all is easy enough for you or what pain points still exist.

I think I should also update my codespaces doc with the process to set this up with some screenshots and whatnot

**Comment by adamwhitlock1** [comment]
Added docs for the codespaces here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/92-Codespaces-usage.md#bonus---automatic-public-codespace-creation

I have a bit of a sore throat, but will work on creating a walkthrough screen recording soon.

**Comment by adamwhitlock1** [comment]
Codespace walkthrough video is up here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/92-Codespaces-usage.md#codespace-walkthrough-video

**Comment by msbtterswrth** [comment]
Thanks for the exceptional work on this!
