### ISSUE TITLE
AT Testing

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#113]
### Background 
We want to test our pattern with AT users to make sure we're in compliance with accessibility guidelines.

We want to specifically test if our alerts are being read by screen readers at the right time (or at all) and that tabbing through the page they get focused in the proper order.

Consult with [platform defect severity rubric](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric). 

### ACs
- [x] We have tested our prefill pattern for
    - [x] tab navigability 
    - [x] screen readers using Voiceover on Mac and NVDA on PC
    - [x] we have run our pattern through aXe

**Comment by msbtterswrth** [comment]
Should we engage with CAIA to help us test the pattern?

**Comment by bellepx0** [comment]
Tested on MAC. Findings & questions in this [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a84d4373d190d4620ed84dd69b3a97df917d04ca/products/authenticated-patterns/engineering/%23113-AT%20Testing.md)

**Comment by bellepx0** [comment]
Assigning @adamwhitlock1  to test on PC

**Comment by adamwhitlock1** [comment]
I updated the AT doc with Windows notes and some potential next steps:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%23113-AT%20Testing.md

@bellepx0 I don't think I missed anything, but feel free to add to the list at the end if needed.

@msbtterswrth we will need to create tickets for some of these items for next sprint, and should discuss during refinement / planning further.

**Comment by msbtterswrth** [comment]
Sounds good to me!

**Comment by beckyphung** [comment]
@adamwhitlock1 @msbtterswrth I'm curious how we plan to address the [next steps/open questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%23113-AT%20Testing.md#open-questions-and-proposed-next-steps). Can we make sure to consult with CAIA? Is that noted somewhere already?

**Comment by msbtterswrth** [comment]
We have created a number of tasks for future sprints based on this work: 
- #161 
- #162 
- #163 
- #164 

We just had a meeting with CAIA that may resolve some of these things natively as part of our next pattern as well.
