### ISSUE TITLE
SPIKE Review page edit flow

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#117]
### User Story
We want to investigate how the edit flow might change from the review page to go back into previous form sections

### ACs
- [x] we've determined what the process might be and how long it might take

**Comment by bellepx0** [comment]
Please see discovery doc here 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/140bddf019f1c648b801f196392b3e2cef65b9f3/products/authenticated-patterns/engineering/%23117-%5BSPIKE%5D%20%20Review%20page%20edit%20flow.md

**Comment by msbtterswrth** [comment]
great work, let's talk about this in refinement today for next steps!
