### ISSUE TITLE
Update Platform docs for prefill

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#118]
We want to update platform dev docs for how to implement the prefill pattern so that users can implement the pattern successfully.

### ACs
- [x] discover where our guidance might live in platform docs
- [x] open a platform support task to update content on the document site

**Comment by msbtterswrth** [comment]
Based on the convo we had with Platform content folks yesterday, we'll draft the updates to the page in GH task in their repo which the platform team will then convert into confluence content. 

When you open that task, can you drop a link to it in this task so we can keep track @adamwhitlock1?

**Comment by adamwhitlock1** [comment]
I opened the task here with some basic content to update the docs with along with the links to storybook and to the design system docs for the pattern:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/96528
