### ISSUE TITLE
Create Storybook Components for Prefill Pattern in VADS Guidance [stretch goal]

### ISSUE THREAD

**Issue by bellepx0** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#120]
Develop Storybook components for the prefill pattern to be included in the VADS guidance documentation. 

1. Create “Patterns” Folder in VADS Storybook
- Main parent folder: Prefill
- Two sub-folders: Components and Usage Examples
2. Components to be Created:
a) Prefill Alert Component -> Three variations:
- Unauthenticated Alert
- Prefilled Info Alert
- Signed In Alert
b) Locked Gray Card Component
c) Unlockable White Card with Border Component
3) Usage Examples --> Mock form samples demonstrating how each component is to be integrated into the form

**Keep in mind for following ticket: how and where to share the Storybook components. Potential places include the [VA Forms Library](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill#VAFormsLibrary-HowtoworkwithPre-Fill-Vets-WebsiteWork) docs and the [Form Digitization Development Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/31026b512821e65b90aca5d80afec05393b4b3d1/Engineering/Form%20Digitization%20development%20guide.md).

Acceptance Criteria:
- [ ] All components should be visually aligned with the designs.

**Comment by bellepx0** [comment]
Created draft [PR](https://github.com/department-of-veterans-affairs/component-library/pull/1356) for Matt to review and get team feedback

**Comment by bellepx0** [comment]
Update: Moved the [PR](https://github.com/department-of-veterans-affairs/component-library/pull/1356) out of draft. Tagged Matt as a reviewer letting him know we'd like his feedback. Also added the PR link to the collab cycle ticket under "Staging Review" > "Staging review artifacts" > "Required Artifacts".

**Comment by beckyphung** [comment]
@msbtterswrth Can we make sure to align on the same names of things across all of the different artifacts we're creating. For example, in [our GitHub draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md#how-this-pattern-works) for the "Know when their information is prefilled" page, we use **editable** and **uneditable** to describe the types of cards. 

In the storybook, I see we're using **locked** and **unlocked**. **Editable** and **uneditable** imo is clearer.

**Comment by msbtterswrth** [comment]
CC @bellepx0 if we could update that please

**Comment by bellepx0** [comment]
@beckyphung @msbtterswrth Updated all instances of locked and unlocked to editable and uneditable respectively.
