### ISSUE TITLE
Create fallback landing page for root of mock form app

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#122]
### User Story
As a user of the mock authed patterns form, I need a landing page to allow me to start any of the patterns so that I can easily navigate between patterns.

### Background
The root route of our app at `/mock-form-ae-design-patterns/` doesn't render much other than our patterns heading.

![Image](https://github.com/user-attachments/assets/69aae061-e6d8-4cd2-a7f8-81f1d2c4ff2c)

We should add basic buttons to navigate into either pattern 1 or pattern 2, and make the title dynamic, so that it always shows the current month / year and that way it doesn't need to be updated monthly.

### ACs
- [x] Navigation is available from root route
- [x] dynamic title is updated automatically

**Comment by adamwhitlock1** [comment]
Merged this work and it is now live in staging. You can validate by viewing https://staging.va.gov/mock-form-ae-design-patterns to see the fallback buttons for each pattern. Clicking on either one should take you to that pattern's main task landing page.

Also the page has been updated to use the current month and year dynamically, so that it doesn't have to updated manually.

**Comment by msbtterswrth** [comment]
Fantastic work here! I validated that we have a landing page and that there is a dynamic title as well!
