### ISSUE TITLE
SPIKE Determine best way to reroute users after editing from review page

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#127]
### Background
During our research in #117 we discovered that several team have implemented a similar review process whereby users are returned to the review from the edit step. These teams are using different methods to accomplish this; session storage and query strings. 

We want to determine the best route forward for this pattern.

### ACs
- [x] we have investigated forms with both methods
- [x] we have decided which one is better

**Comment by bellepx0** [comment]
Please see spike doc [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/7fc1f220c08214de8865776799dc718dd4d16171/products/authenticated-patterns/engineering/%5BSPIKE%5D%20%20Review%20page%20edit%20flow.md).

**Comment by bellepx0** [comment]
We have decided to go with using sessionStorage for this pattern (Option 1 in the doc).
