### ISSUE TITLE
Update USWDS discussion ticket

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#158]
### User story 
Now that our research study has been completed, synthesized and our final pattern decided upon, we should update our [USWDS discussion](https://github.com/uswds/uswds/discussions/6053) with our research findings, finalized patter guidance and designs.

### ACs
- [x] We have updated our [USWDS ticket](https://github.com/uswds/uswds/discussions/6053) with our updated learnings and guidance.

**Comment by bellepx0** [comment]
Added comment with updates.
