### ISSUE TITLE
A11y Address tabindex and focus issues

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#161]
### User Story
As a user, I want proper focus management and tabindex attributes on form elements, so that I can navigate and understand the content.

### Background
Our accessibility audit has revealed several issues related to tabindex and focus management across different pages and components.

### ACs
- [ ] Add `tabindex=0` to relevant alerts
- [x] Programmatic focus is added to Success alerts after editing and saving information
- [ ] Ensure proper focus order across all pages

### Review needed by
- [ ] Product Owner 
- [ ] Product Manager
- [ ] Engineering Team

### Definition of Done
- [ ] Reviewers have approved.
- [ ] Changes have been tested with various assistive technologies (e.g., NVDA, VoiceOver)

**Comment by bellepx0** [comment]
AT pilot session on 11/6 validated that the focus management on elements were handled appropriately. Closing ticket.
