### ISSUE TITLE
Update content guide style guide

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#166]
### Background
During our [staging collab cycle review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95781) it was discovered that our new prefill guidance required a change to the [Content Style Guide](https://design.va.gov/content-style-guide/error-messages/engagement).

We need to update the prefill sections here to match our new content.

### ACs
- [ ] Content style guide has been updated to match our new prefill alert content

**Comment by adamwhitlock1** [comment]
I'm not 100% sure what the content is that we are updating on this page, but I used what we have in the storybook and other areas to update the content the best I could. Can you review this page @msbtterswrth 

https://dev-design.va.gov/3480/content-style-guide/error-messages/engagement

This is the 'preview deployment' for a PR I have in draft for this and the other changes to our prefill pattern content.

**Comment by msbtterswrth** [comment]
For the auth alert, I believe there are two versions:

**One where we update the form only** 
> Note: We’ve prefilled some of your information from your account. If you need to correct anything, you can select edit below. All updates will be made only to this form.

**One where we update the profile also**
> Note: We’ve prefilled some of your information from your account. If you need to correct anything, you can select edit below. All updates will also save to your profile. 

Double check the wording on that second one, though. I'm not sure if we need a new row, or if you can put both in the same td with a hard line break.

**Comment by adamwhitlock1** [comment]
Yea I'm not sure that putting it in the same row is great

![Image](https://github.com/user-attachments/assets/83411467-10dd-4ab8-9d25-9b50d3f4ae6e)

Kind feels like it need differentiation? What do you think

**Comment by msbtterswrth** [comment]
Yeah, let's make a new row! 

**Prefill - Step variation (for authenticated users) - Form only**

**Prefill - Step variation (for authenticated users) - Profile and Form**

**Comment by beckyphung** [comment]
@msbtterswrth I may have missed this if you mentioned it, but given our update prefill recs, it sounds like we'll also need to make the same content update on this page?

**Comment by msbtterswrth** [comment]
yes we'll def need to update this page, we [have a ticket](https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/253) but it's mostly empty right now as we wait feedback. I'll mention this there just so we don't forget!
