### ISSUE TITLE
Add messaging to current know how your info is updated pattern

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#168]
### Background
As part of our (staging collab cycle review)[https://github.com/department-of-veterans-affairs/va.gov-team/issues/95771] we want to clarify the status of the "Know how your info is updated" pattern as it relates to the new pattern.

We should investigate adding messaging to this page (and the prefill alert page) that lets users know this page is under construction and will be updated soon.

### ACs
- [x] Talk to CAIA about messaging we could add for under construction pages
- [x] Investigate if there are existing examples
- [x] Add recommended messaging to our pages in VADS
    - [x] Prefill Alert Page
        - [x] We may be replacing this page soon. [See the new prefill pattern page for up-to-date guidance. ](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled)
    - [x] Existing Pattern Page
        - [x] We are updating this pattern. Please note that some guidance may be out of date. [See the new prefill pattern page for up-to-date guidance. ](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled)

**Comment by msbtterswrth** [comment]
I reached out to the platform design team [on slack](https://dsva.slack.com/archives/C01DBGX4P45/p1729176181758309) and we determined there was not any pre-existing guidance or examples of content like this however using a warning or info alert may be the best route.

On the [prefill alert page](https://design.va.gov/components/form/prefill), we'd like to add a message saying "this page may be deprecated soon, please see the new prefill pattern page" or something similar.

On the [existing pattern page](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated), we'd like to add a message saying "this pattern will be updated soon and some guidance on this page may be out of date" or something similar.

Let's reach out to CAIA for some help determining the right language, if we think we need it.

CC @kristen101606 @ChristineRoseSteiffer

**Comment by msbtterswrth** [comment]
@KKitagawa-Bosch is this something you could help us write?

**Comment by KKitagawa-Bosch** [comment]
@msbtterswrth absolutely! Just checked with my PM and have the green light to help out

**Comment by msbtterswrth** [comment]
AMAZING! We'd like feedback on adding an alert to those two pages.

We'll be investigating updating/removing the prefill alert page this sprint, and so would like to add a temporary alert to link to our recently created prefill pattern page and let users know the content may be outdated.

We're also in the process of submitting our research plan for updating the 'know how your information is updated' pattern and so we'd like to alert users that it's contents WILL be changing soon.

**Comment by msbtterswrth** [comment]
@KKitagawa-Bosch just checking in to see if you had any time to review or guidance to share for this request?

**Comment by KKitagawa-Bosch** [comment]
@msbtterswrth ah how strange I didn't get a notification last week that you commented, sorry! I've got a pretty free day today luckily, so I'll get to this today!

**Comment by KKitagawa-Bosch** [comment]
Here's my first thoughts/recommendations: 

**Prefill Alert Page**
We are replacing this page soon. See the new prefill pattern page for up-to-date guidance. (second sentence can be a link). 

**Existing Pattern Page**
We are updating this pattern. Please note that some guidance may be out of date. (is there a link we could include as the third sentence?)

**Comment by msbtterswrth** [comment]
Sounds fantastic! We can include a link to the other prefill page perhaps using the same sentence as the first alert.


@bellepx0 @adamwhitlock1 could one of yall add alerts with the above content on the two pages in our next PR for updates?

**Comment by adamwhitlock1** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3491
