### ISSUE TITLE
Investigate prefillMessage component

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#169]
### Background
There exists a prefillMessage component that is considered a 'content component'. Currently this is meant to be used to pull in standardized static alert content for prefill alerts, though few forms are using it correctly (or at all).

We want to investigate it's usage and propose a path forward for it and it's VADS page. Those forms that are using this component often do so incorrectly and overwrite the default content anyways, so it may benefit us to remove the option for overwriting that, if the desire is to have consistent messaging across all form contexts. 

We know that the prefillMessage component does NOT currently use the correct alert component, it's using a plain div with a blue background.

### ACs
- [x] We have documented all the forms using this component
- [x] We have documented it's variations
- [x] We have determined if we should keep the component as is or update it
- [x] We have created follow up tasks to adjust our VADS guidance if necessary

**Comment by adamwhitlock1** [comment]
I have created a markdown file for my findings and suggested steps for standardizing the component.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/169-PrefillMessage-platform-usage.md

**Comment by msbtterswrth** [comment]
Excellent work! Let's chat about this during refinement today and what our next steps are!

**Comment by beckyphung** [comment]
@msbtterswrth Given the findings, what is our recommendation for the prefill component page? Sounds like majority of teams are using this component.

**Comment by msbtterswrth** [comment]
I believe we decided to leave as is @adamwhitlock1 @bellepx0 can check me on that though
