### ISSUE TITLE
Update Service History sections

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#171]
### User Story
We need to build out the new service history pattern within our prototype forms. This is currently blocked by decisions from the VFF team.

### Background
22-1990 needs an updated mil history section

### ACs
- [ ] Update for review InfoSection style design
- [ ] Figure out how adding and editing service periods would work and if editing removes all prefilled periods

### Review needed by

- [ ] VA Product Owner 
- [ ] Product Manager
- [ ] UX Research Team
- [ ] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by adamwhitlock1** [comment]
Closing this since we aren't using military history for research sessions.
