### ISSUE TITLE
Refine designs and research documentation based on feedback

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#172]
We need to refine our designs after we have gotten feedback about the service history pattern and presented them to our POs including Matt Dingee.

### ACs 
- [x] We have updated our figma files based on feedback 
- [x] We have updated or removed our service history sections
- [x] We have updated our research plan and conversation guide with the finalized guidance
- [x] Our designs have been finalized and are ready to be submitted with the research plan

**Comment by beckyphung** [comment]
@msbtterswrth Could you make sure to include links to the deliverables? For most tickets, I see the linked items. Looks like this one was just an outlier.
