### ISSUE TITLE
VADX - file organization and cleanup for best practices

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#190]
### User Story
As an engineer I want to discover how we can clean up organization of our files in the existing mock form folder and improve maintainability.

### Background

Idea to explore:

  - Our typical react organizational scheme is dated, and could use re-evaluation, especially for our use case of rapid iteration of ideas.
  - https://feature-sliced.design
  - [Bulletproof react](https://github.com/alan2207/bulletproof-react) is one example structure that has some viable ideas to consider.
  - [Other potential folder structures via webdevsimplified](https://blog.webdevsimplified.com/2022-07/react-folder-structure)
  - [Official react docs on folder structure](https://legacy.reactjs.org/docs/faq-structure.html)

### ACs
- [x] we have landed on a path forward and have created follow up tickets to re-organize folder and file structure.
- [x] file organization has been updated

### Review needed by

- [ ] VA Product Owner 
- [ ] Product Manager
- [ ] UX Research Team
- [ ] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by beckyphung** [comment]
@adamwhitlock1 or @msbtterswrth could someone add a link to our files, so I can see the reorganization?

**Comment by msbtterswrth** [comment]
You can see the PR linked above in the thread but here it is again: https://github.com/department-of-veterans-affairs/vets-website/pull/33301

here's the [direct link to the repo](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/_mock-form-ae-design-patterns)

**Comment by beckyphung** [comment]
Ah thank you, sorry missed this!
