### ISSUE TITLE
Create Research Report and Deck

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#250]
## User Story
As a member of the AEDP team I want to create our research report and presentation deck so that I can share our team's findings and recommendations about the Update prefilled information pattern with other VA teams.

We'll be presenting to the Design team on Monday the 16th.

## Deliverables

- [x] Research report [(sharepoint)](https://dvagov.sharepoint.com/:w:/s/TMFAuthenticatedExperienceDesignPatterns/Ee0Fzta676BPkLAbldtU5aoBewJwz7wvtDgT_9p5aDUqVg?e=mbKiYL)
- [x] [Presentation deck](https://docs.google.com/presentation/d/1CpraAZvELqO5SXiuxyq7A0ZWRWOo5OYm4AUXYGSWRFg/edit#slide=id.g26b8e480611_1_0)

## Acceptance Criteria
- [x] Deliverables have been created
- [x] Equality checker has been updated
- [x] Deliverables have been reviewed by internal team members
- [x] Research report has been updated within
    - [x] Research Ticket
    - [x] EHQ 
    - [x] Sharepoint

### Review needed by

- [x] VA Product Owner 
- [x] Product Manager
- [x] UX Research Team
- [x] Engineering Team

### Definition of Done

- [x] Documentation has been updated, if applicable.
- [x] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by ChristineRoseSteiffer** [comment]
Draft [report ](https://docs.google.com/document/d/19Cbrn9oL4BKwCCSuwmXShxpsq7MgT5enxumBELPH4Ds/edit?tab=t.0)is in google docs for now until it is finalized and will be moved to GitHub.

**Comment by msbtterswrth** [comment]
@beckyphung I think this is ready for your review!

**Comment by beckyphung** [comment]
Thanks for sharing and sending the Slack message! Here's my feedback: 

- This matches the findings template. And I see we've included # of participants in the findings. If there's a way to summarize # of participants at a higher level in the IA, that would be helpful for skimming. 
- Content: I started making suggestions to break up longer sentences. This helps with being concise and helps anyone reviewing our docs get to the point of what we're trying to say. This goes for other documentation we might need to create too. For example: 

   > Original: While users didn’t organically notice the difference between how the Social Security number was displayed between tasks, when reviewed side-by-side there was a slight preference for the “Last 4 digits...” format. 

   > Revised: Users didn’t organically notice the difference between how the Social Security number was displayed between tasks. When reviewed side-by-side, there was a slight preference for the “Last 4 digits...” format. 

- Preference vs. Usability: For the next round of research, I'd like to see less around preferences/expectations and more around usability. Thinking about what user stories we have within our pattern helps. For example: 
> Original research goals: 
> - Understand how users expect their prefilled data to be displayed across a given form.
> - Understand user expectations around what the prefill alert should look like across different pages.
> - Understand how users expect the edit process to work and where they expect their edits to get saved.
> - Understand user expectations around why certain data can be edited within their profile and other data cannot.

> Revised research goals (one option):
> - Understand whether users know when information is prefilled
> - Understand whether users understand how to update prefilled information

> Revised research goals (another option):
> - Identify optimal design pattern to help users update their prefilled information
> - Identify any barriers that could prevent Veterans who use assistive technology from updating prefilled information

**Comment by beckyphung** [comment]
I was thinking [something like this](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/veteran%20support%20crew/Contact%20us%20page/User%20research/09-2024%20Find%20help%20on%20Contact%20us/Findings.md#hypotheses-and-conclusions). The goal being to understand the scope of participants who support each hypothesis and/or insight.

**Comment by ChristineRoseSteiffer** [comment]
I've added this sentence to the beginning of the report:

"We spoke with 9 Veterans about 3 different forms across both desktop and mobile views." 

[Sharepoint](https://dvagov.sharepoint.com/:w:/s/TMFAuthenticatedExperienceDesignPatterns/Ee0Fzta676BPkLAbldtU5aoBewJwz7wvtDgT_9p5aDUqVg?e=mbKiYL)
[EnjoyHQ](https://app.enjoyhq.com/projects/pdMxq2PRp/overview)
[Research Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/715)

This ticket is complete. Let me know if there are any remaining questions! Thanks.

**Comment by ChristineRoseSteiffer** [comment]
Thanks for clarifying! I've updated the following documents with that additional column, as well as adding a line to the beginning of the report giving a quick summary of who we talked to. Here are the relevant documents for this ticket. I think it can be closed, but let me know if there are any other edits you think we should make. Thanks!

[Google](https://docs.google.com/document/d/19Cbrn9oL4BKwCCSuwmXShxpsq7MgT5enxumBELPH4Ds/edit?tab=t.0)
[Sharepoint](https://dvagov.sharepoint.com/:w:/s/TMFAuthenticatedExperienceDesignPatterns/Ee0Fzta676BPkLAbldtU5aoBewJwz7wvtDgT_9p5aDUqVg?e=mbKiYL)
[EnjoyHQ](https://app.enjoyhq.com/projects/pdMxq2PRp/overview)
[Research Ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/715)

**Comment by ChristineRoseSteiffer** [comment]
Great! Here is the [link](https://docs.google.com/presentation/d/1rfIqIe4VqqaYjls7aqNaItbWWN0p6_-mE7J1P5Bv1X8/edit#slide=id.ge2a21743f5_0_124 ) to our slide deck for Monday - feel free to add comments to it if you have any! Otherwise I think we can close this ticket.
