### ISSUE TITLE
Update platform docs site with codespaces updates

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#254]
## User Story
As an engineer withing the VA ecosystem, I want to contribute our work on codespaces documentation back up to the platform. 

## Background 

We have created [codespaces documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Engineering/92-Codespaces-usage.md) within our repository, but we want to share this documentation with a wider audience.

## Questions to Answer

- [ ] are there any updates we need to make to our existing documentation before contributing
- [x] are other teams working on similar docs
- [x] where should this documentation live within platform docs

## Deliverables

- [x] Platform ticket to update the docs site

## Acceptance Criteria
- [x] Deliverables have been created
- [x] Deliverables have been reviewed by internal team members

### Review needed by

- [ ] VA Product Owner 
- [x] Product Manager
- [ ] UX Research Team
- [x] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by bellepx0** [comment]
Platform ticket created [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99671)

**Other teams with Codespaces documentation in their own repos**

1. health-care/checkin --> [Using Codespaces](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5d90d3c91de22817a3fb82e423de1e79f6caf6c7/products/health-care/checkin/team/using-codespaces.md)
2. health-care/digital-health-modernization/mhv-to-va.gov --> [Creating codespaces](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5d90d3c91de22817a3fb82e423de1e79f6caf6c7/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/research/creating-codespaces-how-to.pdf)
3. health-care/secure-messaging/va-secure-messaging --> [Codespaces testing environment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5d90d3c91de22817a3fb82e423de1e79f6caf6c7/products/health-care/secure-messaging/va-secure-messaging/engineering/mhv-codespaces-test-environment.md)

**Other mentions of using GitHub Codespaces within va.gov repo**

1) [teams/cross-team-initiatives/developer-experience/Developing with Github Codespaces.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5d90d3c91de22817a3fb82e423de1e79f6caf6c7/teams/cross-team-initiatives/developer-experience/Developing%20with%20Github%20Codespaces.pptx#L2)
2) [platform/engineering/request-for-comment/supported-development-environments.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/5d90d3c91de22817a3fb82e423de1e79f6caf6c7/teams/cross-team-initiatives/developer-experience/README.md#L8)

**Comment by msbtterswrth** [comment]
Excellent! Do you want to/need to join a platform content office hours to discuss or will the task be opened sufficient?
