### ISSUE TITLE
Current prefill pattern locations are identified and documented

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#33]
### Background
As a AEDP team member i want to understand where and when prefill patterns exist within the existing Authenticated Experiences in the VA platform/products so that I can better document and improve the pattern for contribution to USWDS.

### ACs
- [x] Document all current prefill patterns in use

**Comment by adamwhitlock1** [comment]
Document with existing prefill language or component usage.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/Prefill-existing-usage-notes.md

**Comment by msbtterswrth** [comment]
Looks fantastic! TYSM

**Comment by beckyphung** [comment]
Link got broken. You can find the [notes in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Prefill-existing-usage-notes.md) here
