### ISSUE TITLE
Create design variations drafts

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#35]
### Background
As a AEDP team member I want to create variations for the patterns so that we can test usability.

We have identified three test tracks, including a control.

### Control:
1010EZ form in current state
![image](https://github.com/user-attachments/assets/b58ec64a-5104-42b4-b93e-33bd2f4e92a9)

### Variation 1:
1010EZ form with updates
![image](https://github.com/user-attachments/assets/d22a2396-7a8a-4227-99a5-d7fcf8d36fb0)

### Variation 2:
![image](https://github.com/user-attachments/assets/0c5b4e99-0b99-44e4-917b-06f3bfac75ee)

### ACs
- [x] Up to two design variations exist for each pattern/track
- [x] Initial engagement with CAIA on variations review for content and accessibility

**Comment by msbtterswrth** [comment]
I did some work to create a user journey flow with potential variation points in the darker pink. You can find this in our ["prefill in the wild" mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721249754513/f02ba038a943ebb6dbe07355b5b1d473f42dc16b?wid=0-1721933912072&sender=u11b5f7711188298523d03159).

![Image](https://github.com/user-attachments/assets/a20dd325-17ea-479c-a1ab-b31a2e535907)

I think we should be testing these main things:
- when and where the prefill alert appears
- whether to show prefill inputs or edit in place pattern for items that are prefilled
- show a message for the fields being update-able in-flow or needing to update on profile

**Comment by ChristineRoseSteiffer** [comment]
Here is the [link](https://www.figma.com/design/2j01RTqCSJRy4lX3eUOiod/AE-Design-Patterns---Prefill?node-id=11-52&t=vbAluWyNiGIcnsLC-0) to the design files for this ticket. The draft designs are done, and now we are working through reviewing with out PO in order to arrive at the finalized testing scenarios. The elements we are testing have already been reviewed through CAIA, so we may want to bump out reaching to them to the next sprint.

**Comment by msbtterswrth** [comment]
@ChristineRoseSteiffer are we ok to close this one? I wasn't sure if there was another one floating around for 'finalize' designs, or if we decided to use this one still.

**Comment by msbtterswrth** [comment]
Closing as completed!
