### ISSUE TITLE
 Current profile patterns are identified and documented

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#37]
### Background
As a AEDP team member I want to know about all the different VA profiles, where they live and how they work so that I can create a more unified profile experience so that Veterans can better maintain their profile data.

- Assemble links to documentation around the VA.gov profile, MHV profile, and any other profile related functionality currently present on VA or VA-adjacent properties.
  - Murals, figma files, and any other useful resources
 
- Outline data sources for VA.gov profile, specifically about what services are used to connect veterans to their information 

ACs
- [x] All VA product profiles are documented including
    - [x] links to product - VA.gov-team repo or other official docs to product if possible
    - [x] description of product
    - [x] behavioral outliers
    - [x] data sources for profile information

**Comment by adamwhitlock1** [comment]
Here is what I've assembled so far

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%2337-discover-current-profile-patterns-and-data.md
