### ISSUE TITLE
Audit existing profile fields

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#43]
### Background
As a AEDP team member, I want to know what profile fields exist, where their data comes from and if they are editable.

### ACs
- [x] An audit of all VA profile fields exists
    - [x] includes a column for if it's editable
    - [ ] includes a column for if it's imported
        - [x] includes data about where it comes from

**Comment by msbtterswrth** [comment]
This is related to #37

**Comment by adamwhitlock1** [comment]
I don't think any of the fields are 'imported' from anywhere per say. Everything comes from vets-api, and it makes requests directly to the providing services like VA Profile and Lighthouse.

I've completed the table here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%2343-profile-field-summary.md

Closing this now and if we need more details we can also refer to the BE docs for profile pages here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile#backend
