### ISSUE TITLE
set up intro call with Perigean

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#45]
We need to set up an introductory call with Perigean to get onboarded into their process and ask questions about our first research study. 

dependent on #41

**Comment by ACParker89** [comment]
This call has been made, @ChristineRoseSteiffer provided time slots and are waiting on a response. 

@Jones-Morgan will create a list of questions about their process in prep for the call

CC: @beckyphung

**Comment by ChristineRoseSteiffer** [comment]
Call with Perigean went well today! Closing this task
