### ISSUE TITLE
Finalize research plan

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#46]
### User Story
As a member of the AEDP team, I need to finalize my research plan so that it can be submitted for review before we schedule our user study.

### Background
Once the research design variations have been drafted, we can finalize the research plan documentation.

### ACs
- [x] Research plan has been updated with appropriate reference to the designs and test tracks chosen
- [x] Research plan has been reviewed by Design team and PO
- [x] Research plan has been added to the va.gov-team repo
- [x] Research plan has updated **Recruitment** section after we conduct pre-pilot session on Thu 8/15
- [ ] Research plan has been reviewed by OCTO Research team

**Comment by ACParker89** [comment]
@Jones-Morgan will add the google doc with draft

**Comment by Jones-Morgan** [comment]
@beckyphung [Live version of Conversation Guide](https://docs.google.com/document/d/1hnJfa-jPCnYSKXENaWp81ailvdKh9mGnHuiJvukkCd8/edit?usp=sharing)
[live version of Research Plan](https://docs.google.com/document/d/19MxkeXFAAOW67HJ0T9kGept55b2sHcpRYOzx9OZPVao/edit?usp=sharing)

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer @Jones-Morgan I made some final edits to [the research plan](https://docs.google.com/document/d/19MxkeXFAAOW67HJ0T9kGept55b2sHcpRYOzx9OZPVao/edit), particularly the hypothesis section, so it's more concise. 

**Planning questions** @ChristineRoseSteiffer @ACParker89 @msbtterswrth 
- I'm not sure if we can say the research plan is finalized until we decide on the methodology. And we'll determine that after our pre-pilot on Thursday. Would it be more accurate to update the issue to be "Finalize research plan without methodology"? And then have another issue that finalizes the plan after we determine the methodology (i.e. test with three flows or two flows per participant)? 
- Can we also be more specific in the ACs? For example, I consider this finalized when it's been updated in GitHub. So could we add or revise an existing AC to include "added to GitHub" and then link to the md doc?

**Comment by Jones-Morgan** [comment]
> @ChristineRoseSteiffer @Jones-Morgan I made some final edits to [the research plan](https://docs.google.com/document/d/19MxkeXFAAOW67HJ0T9kGept55b2sHcpRYOzx9OZPVao/edit), particularly the hypothesis section, so it's more concise.
> 
> **Planning questions** @ChristineRoseSteiffer @ACParker89 @msbtterswrth
> 
> * I'm not sure if we can say the research plan is finalized until we decide on the methodology. And we'll determine that after our pre-pilot on Thursday. Would it be more accurate to update the issue to be "Finalize research plan without methodology"? And then have another issue that finalizes the plan after we determine the methodology (i.e. test with three flows or two flows per participant)?
> * Can we also be more specific in the ACs? For example, I consider this finalized when it's been updated in GitHub. So could we add or revise an existing AC to include "added to GitHub" and then link to the md doc?

I agree with this. The pilot and run-thorough will help to ensure this is accurate. However, I have updated it in Github so a bulk of that work is done: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-07-Research%20Initiative-One-Prefill/preFillresearchPlan.md

**Comment by beckyphung** [comment]
We agreed [in this Slack thread](https://dsva.slack.com/archives/C07909N7U8Z/p1723578825305499) that we'll push this issue to the next sprint:
> From Lynn to Morgan: i would leave it open and we'll push it

**Comment by msbtterswrth** [comment]
Pushing to next sprint, so we can have the pre-pilot session.

**Comment by beckyphung** [comment]
> ...so that it can be submitted to CAIA for review before we schedule our user study.

I just noticed this part of the user story. I don't think we need CAIA's approval. I would like to do a final review before we submit to Shane for review. [Here's an example] (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ask-va/design/User%20research/04-2024%20Progress%20bar/Conversation%20guide.md#approved-by) of how my other team's documented the approvals in the research plan.

Could someone update the description to reflect this change, including adding ACs? @ChristineRoseSteiffer ? Also, does this ticket include getting Shane's approval, or is that in another ticket?

**Comment by msbtterswrth** [comment]
@beckyphung what team is Shane on? I added an AC for 'review with appropriate VA teams' but I'd like to update it with their actual team.

**Comment by beckyphung** [comment]
@msbtterswrth Sorry here's more context - Shane is our OCTO research lead. When we create a request during the [research review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) step in the collab cycle, Shane's going to review our research plan and convo guide.

**Comment by Jones-Morgan** [comment]
@beckyphung @ChristineRoseSteiffer the research plan has been updated to reflect our discussion about recruitment criteria after the pre-pilot yesterday: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-07-Research%20Initiative-One-Prefill/preFillresearchPlan.md

**Comment by msbtterswrth** [comment]
Moving the last AC of "Research plan has been reviewed by OCTO Research team" to the follow up task of #41 and closing this one.
