### ISSUE TITLE
build out prototypes for variations

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#47]
### Background
As a researcher, I need to have prototypes for each of the variations I plan to test so that while I'm conducting research my test subjects can interact in real time with our designs.

Building each prototype to live in staging will entail setting up the pages, ensuring that authentication is handled and that prefill works as expected.

ACs
- [ ] prototypes are built on staging for the following design variations
    - [ ] control scenario (1010EZ - current state)
    - [ ] variation 1 (1010EZ modified)
    - [ ] variation 2 (10182 modified)

**Comment by adamwhitlock1** [comment]
We should probably break these out into their own tickets, so one task scenario/variation per ticket as this feels like a bit much for a single ticket and also could be split between engineers easier that way.

**Comment by msbtterswrth** [comment]
Closing in favor of #51 #52 #53 and #54.
