### ISSUE TITLE
Synthesize Medallia survey feedback on 'Prefill'

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#48]
As a Design Patterns team member, I want to review the Medallia survey data for the keyword 'prefill' to see if there are any insights we can gain from this data.

ACs
- [ ] Survey data is analyzed
- [ ] Analysis is shared with the team 
*We weren't able to complete these AC's because of a lack of data.*

**Comment by Jones-Morgan** [comment]
This has been done. There was only one line regarding "prefill" and the person simply requested for it to exist. The results were not informative. 
the next steps I'm taking are to work with the data scientist to see if more can be gleaned.

**Comment by beckyphung** [comment]
@msbtterswrth @ACParker89 I'm not sure why this was closed because:
- The analysis isn't linked anywhere
- The analysis wasn't shared with the team (?) 
- The ACs aren't checked off

**Comment by ACParker89** [comment]
@Jones-Morgan - can you add comments/links/etc? 

> @msbtterswrth @ACParker89 I'm not sure why this was closed because:
> 
> * The analysis isn't linked anywhere
> * The analysis wasn't shared with the team (?)
> * The ACs aren't checked off

**Comment by Jones-Morgan** [comment]
There was only one result so there wasn't enough information to synthesize: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1724345486226/599db2d47108c6e31bd6418c8b58dbc04d1fd08b?sender=u649de617cef06172cf5f0271
Here is the original spreadsheet: https://docs.google.com/spreadsheets/d/12bn8HlYIYzIzBPOv9abUreanfp3fGANtQX7_gRrQuqg/edit?gid=657256714#gid=657256714

**Comment by Jones-Morgan** [comment]
@msbtterswrth it may be worth focusing this query on just the forms that offer the prefill experience. I'm tagging you because it may be worth bringing this up in our next Monday meeting.

**Comment by beckyphung** [comment]
Got it, seeing the results makes more sense to me. Also note on using Google Docs - let's keep Medallia responses in Excel on the network, because people often (even though they're warned not to) put PII/PHI in their responses. 

Before closing, @Jones-Morgan can you update the description to describe that we weren't able to complete those AC's because of a lack of data?

**Comment by Jones-Morgan** [comment]
That is done now. Thanks.
