### ISSUE TITLE
FE Prefill Pattern - Build Control Variation 1010EZ - Task Green

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#51]
## Issue Description

As a developer I want to have the Control Scenario created and live in staging as the first part of building out these patterns for research.

BONUS:
Github Codespaces are a way to spin up a specific branch of code within a live url and share that url with users publicaly. It is an alternative to using staging when presenting a prototype or non-production code and can be used to view the va.gov applications within a limited capacity.

As an engineer I would like to use Codespaces to provide a public URL to a prototype and haver that prototype talk to the mock api. I will use the branch that is merged to staging to spin up the Codespaces instance.

## Front end tasks
- Implement auth workarounds so that localstorage doesn't prevent authenticated requests from occurring
- Use query param to trigger authed vs unauthed view
- Build the control scenario form within a branch of vets-website and deploy it to staging.

- Bonus: get the staging branch running in Codespaces
- Review with team about walking through the research task using the codespace

## Acceptance Criteria
- [x] Control scenario is live on staging
- [x] Auth can be mocked / triggered as true for prototyping

Bonus:
- [ ] Codespace also has first scenario
- [x] Mock server responds with the required prefill info to display what the user expects

**Comment by adamwhitlock1** [comment]
I'm in the home stretch of this task. PR is up here: https://github.com/department-of-veterans-affairs/vets-website/pull/31338 I am planning on reviewing it with Belle in tomorrow so that we can go through it together (its kinda huge) and then we can get it pushed up to staging.

I'm unsure if the auth mocking is going to work in staging as is, but will just have to see once it actually deploys there.

**Comment by adamwhitlock1** [comment]
This has been merged and is live in staging.

The mocked auth isn't quite functioning as we would like, but it works to the extent that:
- If you **log in first** and then visit the url https://staging.va.gov/mock-form-ae-design-patterns/task-green/introduction?loggedIn=false you will indeed see what the un-authenticated experience would be for the first introduction page, then when you click the 'sign in to start you form' button, you are redirected back to the introduction page with the authenticated experience loaded
- We will continue to see what we can to do mock out the auth side of things further, but codespaces might be the easiest way to circumvent auth altogether.

You can now click through the form and view the completion step at the end and also reload the form task by clicking the buttons at the bottom of the form.

@bellepx0 can you confirm that you can see this form as well? Then I will close out this ticket as the main items have been completed.

**Comment by bellepx0** [comment]
@adamwhitlock1 Confirming that I followed your instructions and the form functions as stated. 🥳
