### ISSUE TITLE
Finalize designs

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#61]
### User Story
As an AEDP team member I need to finalize variation designs so that I can finalize my research plan and the engineering team can finalize their prototypes.

### Background
We should schedule a meeting with Matt/Becky (maybe Kevin) to review by the end of sprint.

### ACs
- [x] Designs have been internally reviewed
- [x] Designs have been presented to our POs

**Comment by kristen101606** [comment]
Designs are drafted in the [Research Study Figma page](https://www.figma.com/design/1z3bAkQl4uR1IvAxmtyqZi/AE-Design-Patterns---Update-Prefill?node-id=3387-40809&t=jtwiX2vPAhxYW6U0-1). We're meeting with VFF tomorrow to discuss if/how we'll integrate their WIP service history designs into our Orange flow. Once we have that sorted out, these designs will be ready for teamwide and PO review.

**Comment by msbtterswrth** [comment]
Designs are in a good place to close this task out, we'll open another task for updates related to feedback from Matt and Becky in the next sprint.
