### ISSUE TITLE
Submit research plan

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#63]
### User Story
As a member of the AEDP team I need to submit our research plan so we can schedule our usability study with Perigean.

### Background
We need to submit two requests, one for AT users and one for non-AT users. 

### ACs
- [ ] Our research plan has been submitted for review and scheduling

**Comment by ChristineRoseSteiffer** [comment]
Added the research and recruiting tickets to the task description. The tickets have been submitted and this ticket can be closed.
