### ISSUE TITLE
Submit pattern for Staging review

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#65]
### User Story
As a member of the AEDP team I need to submit our pattern to the collab cycle staging review so that it can be adopted into the VA design system.

### ACs 
- [x] A collab cycle Staging Review task has been created
- [x] Staging review has been scheduled
- [x] All required artifacts have been added to the staging review

**Comment by msbtterswrth** [comment]
blocking until we get more insight from our synthesis in https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/81

**Comment by bellepx0** [comment]
Staging review ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97906)

**Comment by msbtterswrth** [comment]
@adamwhitlock1 please open a PR and link the review instance ty!

**Comment by msbtterswrth** [comment]
Staging review tasks can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/98543
