### ISSUE TITLE
Create VADS draft governance content

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#67]
### User Story
As a member of the AEDP team I need to create content for the VADS page so that teams can understand the new pattern and it's guidance.

### Background

Page content should follow the guidelines found at: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/blob/main/src/_patterns/template.md

A good example of a more recently updated pattern is https://design.va.gov/patterns/ask-users-for/email-address, we should be sure reference this as a guide.

### ACs
- [x] Determine which component or other pages need to be updated
- [x] A template has been created with formatting and an outline for the VADS page
- [x] VADS code contribution path

**Comment by beckyphung** [comment]
[Ask users for… Email address](https://design.va.gov/patterns/ask-users-for/email-address) is an example of one of the more updated patterns. I know it's "more updated" because it links to the [web-component pattern available in the Forms library](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/web-component-patterns/emailPattern.jsx) in the **Code usage** section. Mentioned this in our call earlier today

**Comment by msbtterswrth** [comment]
I have begun a [draft guidance doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md) in our vagov-team repo

**Comment by msbtterswrth** [comment]
We are recommending removing the following page (to be absorbed by a new page): 
- https://design.va.gov/components/form/prefill

Updating the following page (to remove prefill alert related things): 
- https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated

And creating a new page:
- https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled (does not exist yet)

**Comment by beckyphung** [comment]
@msbtterswrth What are we expecting happens to [Know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)? Maybe this page could be the new page for #22 Update prefilled information?

**Comment by bellepx0** [comment]
Created a [Discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/46dcd5e98aaafcee84c7fd648fefa42146c26199/products/authenticated-patterns/engineering/%2367-Code%20contribution%20for%20VADS%20governance%20content%20for%20prefill%20pattern.md) for the Code Usage section 

The doc also shows examples of how this pattern would be presented in Storybook if we choose to go that route.

**Comment by ChristineRoseSteiffer** [comment]
Since we are working through our study synthesis next sprint, the draft content for many of these ACs will come along with that. Should we move those tasks into a story for next sprint, or carry this whole ticket over? It seems like a lot of good work has already been done here so I'd be more inclined to do the first option.

**Comment by msbtterswrth** [comment]
Agree, will split out a story for the actual _content_ drafting for next sprint. We have completed the following in this sprint:
- created a draft artifact for contributing (formatting and outline)
- created documentation for how to submit code along with our guidance
- determined which pages need to be updated, added or removed

**Comment by beckyphung** [comment]
@msbtterswrth @bellepx0 When we say **Prefill pattern**[ in this code usage GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/46dcd5e98aaafcee84c7fd648fefa42146c26199/products/authenticated-patterns/engineering/%2367-Code%20contribution%20for%20VADS%20governance%20content%20for%20prefill%20pattern.md), which pattern are we referring to?
- Know when their information is prefilled? #17 OR
- Update prefilled information #22

**Comment by msbtterswrth** [comment]
This task (and it's  documentation) refer to #17.
