### ISSUE TITLE
Review pattern with Mini DSC

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#68]
### User Story
As a member of the AEDP team I need to prepare our pattern for review with the Design System Council, so that we can finalize it before it goes through the staging review in collab cycle before adoption.

### ACs
- [x] Schedule meeting with mini DSC crew
- [x] Investigate DSC review process
- [x] Create needed artifacts
- [x] Our pattern has been presented for feedback to the mini DSC 

### Ticket Deliverables
- [Prefill Pattern Slide Deck](https://dvagov.sharepoint.com/:p:/r/sites/TMFAuthenticatedExperienceDesignPatterns/Shared%20Documents/General/Research%20and%20Design/Research%20Artifacts/Authenticated%20Experience%20Design%20Patterns.pptx?d=w8ff594f795c14969a56b4a8eff97b488&csf=1&web=1&e=3iUOZJ)
- Meeting Recording

**Comment by msbtterswrth** [comment]
I'm looking to tentatively schedule this for the 20th with the following folks: 
- Becky 
- Matt
- RyanT
- MarthaW
- ShaneS
- DanielleT

**Comment by msbtterswrth** [comment]
This has been scheduled for Wen the 18th at 11 am ET.

**Comment by ChristineRoseSteiffer** [comment]
I've added the link to our slidedeck in sharepoint to this ticket. @msbtterswrth could you add the link to the recording? I think we can call this ticket done after that.

**Comment by msbtterswrth** [comment]
I've attached the [link to the meeting](https://dvagov-my.sharepoint.com/:v:/g/personal/elizabeth_stahl_va_gov/EYlShZoivelHqZto5J29Xz0BMNtQrZBGhL6HbeGKZArjWQ?e=rvm5mS&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) which can also be found by opening the meeting in teams and clicking the 'recap' tab.
