### ISSUE TITLE
Submit Pattern for Staging Review

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#69]
### User Story
As a member of the AEDP team I need to submit our pattern to the collab cycle staging review so that it can be adopted into the VA design system.

### Background
Review the guidelines for the [staging review point](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review) in the collab cycle. 

### ACs 
- [x] Discover what we need from an engineering perspective
- [x] A collab cycle kickoff task has been [created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request%2Csitewide+CAIA&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D)
- [ ] A collab cycle Staging Review task has been created
    - [ ] a PR has been opened for design.va.gov
- [ ] The Staging Review has been completed
```[tasklist]
### Related Tasks
- [ ] https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/111
```

Artifacts
[Staging Review Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90181)

**Comment by msbtterswrth** [comment]
Reach out to the 1010 team to pilot this for staging review.

**Comment by msbtterswrth** [comment]
1010 team will meet with us Friday, 9/6 to discuss piloting this for us.

**Comment by msbtterswrth** [comment]
1010 teams has asked that we provide designs of the pattern that should implemented in the 1010 form for staging review.

**Comment by msbtterswrth** [comment]
During monday meeting, we talked about whether or not we should submit any code at all or if it's just guidance around how to use existing components. Team is considering a path forward and will make a decision by end of week.

**Comment by msbtterswrth** [comment]
Per @humancompanion-usds, we'll need to open a PR to the design.va.gov repo with our draft content page. 

> You can add draft: true to the yaml at the top of the pattern so that it is not in the navigation and use that to deploy it in [design.va.gov](http://design.va.gov/) and give the URL to the Governance team to review. 

We can also submit the updated figma file though it's not required.

**Comment by msbtterswrth** [comment]
We need to add [this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md) to the repo for design.va.gov

**Comment by adamwhitlock1** [comment]
Spent time today figuring out how to run the docs site locally and fought with Ruby a bit. Got it running, and pushed up a branch with prelim content: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/tree/authed-patterns/aw/add-prefill-pattern-page

Also was able to get this running on a codespace! I thought that was kinda cool, but still have to figure out one of two other things to actually make it work as a preview url.

**Comment by adamwhitlock1** [comment]
@msbtterswrth, @ChristineRoseSteiffer and @beckyphung  I have submitted the page for review in this PR:

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3329

If yall see anything that I should add or fix let me know and I can still push to that branch before it is merged / review is done on it.

**Comment by msbtterswrth** [comment]
PR is open, and I have scheduled the review for the 15th @ 11:30am EST.


![Image](https://github.com/user-attachments/assets/64008401-1a14-4810-ade6-fc9e3f2393a5)

**Comment by msbtterswrth** [comment]
@adamwhitlock1 I wonder if we also need to include in our PR the removal of the [prefill alert page](https://design.va.gov/components/form/prefill) and the [prefill section on the alert page](https://design.va.gov/components/form/prefill)?
