### ISSUE TITLE
Synthesize USWDS feedback

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#72]
### User Story
As a member of the AEDP team, I want to review feedback that the USWDS team has left in [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721240731572/9e57c7f5b8b3a54b98b5025e6701ba9ec6d74c18?sender=u11b5f7711188298523d03159) so that I can get a better understand of what their  goals are for this project.

### ACs
- [x] Feedback has been synthesized [in this GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/07192024%20USWDS%20feedback%20from%20kickoff%20workshop.md)
- [x] Next steps have been outlined

**Comment by msbtterswrth** [comment]
@beckyphung Is it ok if we mark this as closed? We know the team reviewed the feedback from USWDS in the mural and used it to inform which patterns we prioritized and what to include in our first pattern. I don't think we need an explicit document writing those thoughts up, as the outcome of that work was our product roadmap and first pattern.

**Comment by beckyphung** [comment]
@msbtterswrth I'd still prefer documentation of USWDS's feedback in GitHub. Could you add in the notes from [this GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/07192024%20USWDS%20feedback%20from%20kickoff%20workshop.md) I started?

Moving back to In progress.

**Comment by msbtterswrth** [comment]
Added in all the notes to the doc :) LMK if there's anything else we should/could add in there!

**Comment by beckyphung** [comment]
This looks good to me. Thanks for adding to the GitHub doc! Moving to closed.
