### ISSUE TITLE
Discovery: Requirements and Process for Submitting Prefill Pattern to USWDS

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#73]
### User Story
As a member of the AEDP team, I want to submit our pattern for consideration within USWDS so it can be adopted as part of our project goals.

### Background
As part of this special task force we don't strictly need to follow the public contribution guidelines, but we feel that going through the process will help us obtain valuable feedback in real time of our patterns as we build them.

The guidelines for contribution can be found [here](https://github.com/uswds/uswds/blob/develop/CONTRIBUTING.md).

### ACs
- [x] spike to discover how we convert to USWDS
- [x] We have reviewed the open tasks in the [USWDS backlog](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate tasks or existing work
- [x] Additional tasks have been created as needed

**Comment by bellepx0** [comment]
WIP Documentation with discovery work and findings here
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%2373-USWDS%20Contribution%20Discovery.md

**Comment by msbtterswrth** [comment]
We have opened up #97 for next sprint to discover more information and open the task.

**Comment by beckyphung** [comment]
@bellepx0 Could you update the title to reflect the actual work done, since we didn't open the USWDS contribution task this sprint?

**Comment by beckyphung** [comment]
Thanks for the update @bellepx0 ! Moving to closed.
