### ISSUE TITLE
Open USWDS contribution task

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#77]
### User Story
As a member of the AEDP team, I want to submit our pattern for consideration within USWDS so it can be adopted as part of our project goals.

### Background
As part of this special task force we don't strictly need to follow the public contribution guidelines, but we feel that going through the process will help us obtain valuable feedback in real time of our patterns as we build them.

The guidelines for contribution can be found [here](https://github.com/uswds/uswds/blob/develop/CONTRIBUTING.md).

### ACs
- [x] We have reviewed the open tasks in the [USWDS backlog](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate tasks or existing work
- [x] A task has been opened in the [USWDS repo](https://github.com/uswds/uswds)
- [x] We have notified our contacts at GSA that we've opened a task for our pattern so they can expedite it's review

**Comment by msbtterswrth** [comment]
@ChristineRoseSteiffer and @kristen101606 can you drop our research and design artifacts into this task so we can more efficiently open our USWDS task.

**Comment by msbtterswrth** [comment]
Here's a link to our [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-09%20Research%20Initiative%202%20-%20Update%20Prefill/Update%20Prefill%20Research%20Plan.md) which should outline most of the things you'll need to create this discussion task including links to: 
- [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-09%20Research%20Initiative%202%20-%20Update%20Prefill/Update%20Prefill%20Research%20Conversation%20Guide.md)
- [Prototype](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-09%20Research%20Initiative%202%20-%20Update%20Prefill/x)
- [Designs](https://www.figma.com/design/1z3bAkQl4uR1IvAxmtyqZi/AE-Design-Patterns---Update-Prefill?node-id=3387-40809&t=jtwiX2vPAhxYW6U0-1)

**Comment by msbtterswrth** [comment]
@kristen101606 @ChristineRoseSteiffer could yall add a comment to this task outlining what we _think_ the end pattern will be, accounting for feedback in the sessions we've completed to far?

**Comment by bellepx0** [comment]
Initial draft [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/b64e728430407df4b47eea2cbc7df94bc68c6bae/products/authenticated-patterns/patterns/update-prefilled-information/Update-Prefill-USWDS-discussion.md)

After further consideration and discussion with the team, we decided to move this task to next sprint in order to gather more comprehensive data from user sessions, especially from AT users.

**Comment by msbtterswrth** [comment]
blocking until we get more insight from our synthesis in #81

**Comment by msbtterswrth** [comment]
We can begin to pull out our recommendations from our [deck](https://docs.google.com/presentation/d/1NSRT4hg1NUnPVQMVIrXXOxZa93jNQd_mBK7jB-a5naE/edit#slide=id.g301b4a37d66_0_38)

**Comment by bellepx0** [comment]
USWDS discussion for pattern opened [here](https://github.com/uswds/uswds/discussions/6248)
