### ISSUE TITLE
Define Baselines

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#8]
### Background
In order to measure our successes, we need to establish a baseline against which we can compare our future impacts. 

### Business Outcomes this satisfies from [VA PO mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719240863056/54e2c8569725a72e996ae9b2a687867f572f4051?sender=29eb2bcc-d6c0-41e5-bc30-31269b58bd41)
- Define current baseline percentage of VA.gov users that have completed VA.gov profiles
- Define baseline Google Lighthouse performance targets acceptable to both VA and USWDS, such as time to First Contentful Paint (FCP), acceptable Lighthouse performance targets should be met

### ACs
- [x] ~A baseline percentage of VA.gov users with completed profiles exists~
    - A completed profile is defined as a Veteran has provided answers to every VA data point that is relevant to them and they are comfortable sharing with VA.
- [x] A baseline assessment target for Core Web Vitals exists
- [x] A baseline WCAG/508 compliance level is set (#14)

**Comment by msbtterswrth** [comment]
Per Kevin and Matt, no need for us to gather baseline for the number of completed profiles, just be cognizant that  a longer-term goal is to improve that number, hopefully by reducing friction via the new and improved patterns this project submits.

**Comment by msbtterswrth** [comment]
@adamwhitlock1 how are are coming along with the CWV baseline? Did you need any help or additional tasks for that?

**Comment by adamwhitlock1** [comment]
@msbtterswrth I created a bunch of lighthouse reports and was messing around with the CWV chrome plugin, but I don't think it is giving anything more than the lighthouse reports do.

I added a [folder to the sharepoint drive](https://dvagov.sharepoint.com/sites/TMFAuthenticatedExperienceDesignPatterns/_layouts/15/sharedialog.aspx?listId=98d7d440-aa60-4b38-abb3-d2df7163c6c7&listItemId=7&clientId=sharePoint&policyTip=0&folderColor=13&clickTime=1720679854039&mode=copy&ma=0&fullScreenMode=true&itemName=Engineering&channelId=36f96ff4-4bd3-4335-9a66-3298dd362b63&origin=https%3A%2F%2Fdvagov.sharepoint.com) where I put all the lighthouse reports and should be done writing up a mini findings doc about those today, that I will drop in that folder as well.

**Comment by msbtterswrth** [comment]
We also added this documentation to our [docs repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/baselines/Lighthouse-summary-report.md). 

A general summary exists below: 


| URL                             | Performance | Accessibility | Best Practices | SEO |
| ------------------------------- | ----------- | ------------- | -------------- | --- |
| /profile                        | 64          | 100           | 56             | 61  |
| /profile/direct-deposit         | 56          | 100           | 56             | 61  |
| /profile/military-information   | 63          | 100           | 56             | 61  |
| /profile/contacts               | 62          | 100           | 56             | 61  |
| /profile/contact-information    | 51          | 100           | 56             | 61  |
| /profile/personal-information   | 58          | 100           | 56             | 61  |
| /profile/connected-applications | 68          | 100           | 56             | 61  |
| /profile/account-security       | 65          | 100           | 56             | 61  |
| /profile/notifications          | 65          | 100           | 56             | 61  |
