### ISSUE TITLE
QA Prototype

### ISSUE THREAD

**Issue by Jones-Morgan** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#88]
Tasks 
- Review [Prototype](https://musical-doodle-7676579pxr3rxrg-3001.app.github.dev/mock-form-ae-design-patterns/) alongside the [design](https://www.figma.com/design/2j01RTqCSJRy4lX3eUOiod/AE-Design-Patterns---Prefill?node-id=114-8370&t=XSVgsSWtOeu9EGUH-0)
- Prototype has been reviewed for typos
- Review desktop prototype
- Review mobile prototype
- List of issues is created and provided to engineers

```[tasklist]
### AC
- [x] Prototype has been reviewed for typos
- [x] Prototype has been reviewed against the design and matches the design
- [x] Prototype has been reviewed in dekstop
- [x] Prototype has been reviewed in mobile
- [x] Feedback on any issues has been provided to engineering
- [x] Final review has been completed after engineers have updated any issues
```

**Comment by ChristineRoseSteiffer** [comment]
@adamwhitlock1 @bellepx0 we will tag you here with comments from our QA.

**Comment by Jones-Morgan** [comment]
@adamwhitlock1 @bellepx0 I went through the prototype and the design and made note of differences in this doc: https://docs.google.com/document/d/1xOraL1E992HkkoZruDFdd5b3j6zy4M1Ixw00BGzddmc/edit?usp=sharing

**Comment by ChristineRoseSteiffer** [comment]
@adamwhitlock1 @bellepx0 the QA has been completed in both desktop and mobile. I have updated the designs per CAIA's feedback and that is what was used for the QA. Please review the suggested changes in the shared document @Jones-Morgan posted above. Let us know if you have any questions or concerns. Thanks!

**Comment by ACParker89** [comment]
Update: The engineering updates based on QA have been moved to #96

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer or @Jones-Morgan could someone add links to the Figma file where designs were updated in the description? And the link to the prototype that you reviewed?

**Comment by ChristineRoseSteiffer** [comment]
Sure thing - I've added them to the document and will include those links here to if thats helpful.

[Figma files reviewed](https://www.figma.com/design/2j01RTqCSJRy4lX3eUOiod/AE-Design-Patterns---Prefill?node-id=114-8370&t=XSVgsSWtOeu9EGUH-0)
[Prototype reviewed](https://musical-doodle-7676579pxr3rxrg-3001.app.github.dev/mock-form-ae-design-patterns/)

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer Does this include a final review from you and Morgan before I review? I see there's an unchecked box in the description: 
- [ ] Final review has been completed after engineers have updated any issues

**Comment by ChristineRoseSteiffer** [comment]
I have completed a final review of their changes and they all look good to me! I have checked that box if you'd like to give your final review @beckyphung that would be great! Thanks.

**Comment by beckyphung** [comment]
Looks good to me, thanks for clarifying! Moving to closed now.
