### ISSUE TITLE
Prototype path forward

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#92]
We need to decide a few things about our prototypes moving forward:
- staging vs codespaces
- url structure
- prototype longevity
- task naming within patterns

### ACs
- [x] Create [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/92-Codespaces-usage.md) about how we used Codespaces
- [x] Our naming conventions and urls have been solidified and documented
- [x] We have decided how long we'll keep prototypes alive

**Comment by msbtterswrth** [comment]
A lot of the work has been done in #100.

**Comment by adamwhitlock1** [comment]
I created a doc to outline the steps that we have been doing with our research study within Codespaces here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/92-Codespaces-usage.md

This can be a good place to continue refining the approach and adding items to it when we talk with other teams.

**Comment by msbtterswrth** [comment]
During our monday meeting, we discussed that keeping them indefinitely might be a good idea, so that we can revisit them later on in the project to check our progress and use them to show other teams how codespaces can work for research studies.

We could create a spike to make these available on staging with specific staging users for a future sprint.

**Comment by msbtterswrth** [comment]
@beckyphung this is good for you to review the code space docs if you'd like, but we will be demoing it on wednesday!

**Comment by beckyphung** [comment]
I can't make the Wednesday meeting. I'll review this myself, then wait to close this until Wed, if the team has additional feedback. Would be helpful to see if @bellepx0 in particular has feedback from a dev perspective in particular!

**Comment by beckyphung** [comment]
I've reviewed and am looking for more info within OCTO on cost re: Codespaces. Closing for sprint 6.
