### ISSUE TITLE
SPIKE FE Engineering Cleanup and Refactor - Prefill

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#94]
### User Story
As an engineer I would like to cleanup and refactor the 3 tasks that we have bootstrapped for the prefill pattern. 
- The methodology around making three forms in one should be documented, analyzed, and preparation should be done so that we can easily start on our next pattern engineering tasks. 
- Repeated code should be consolidated, reusable common components should be utilized, and file organization should be optimized.
- Tests around any new functionality or new components should be created.
  - navigation tabs
  - landing page
  - basic form flow e2e tests? this might not be needed as they are very minimal flow and these forms are not shipping to production, but I think testing is not a bad idea, time permitting. 
- Further tickets for optimization or refactoring can be created if needed. We should try and really keep PRs below 500 LOC so either break this task into multiple PRs, or create more tasks if the work is extensive.
  - Mock auth and staging environment workarounds. What can we do to make this better? The codespaces work as expected, but we would really like to have a way to get staging to cooperate for our patterns.
  - ~~Could we point just our app in staging to use the Codespaces api url? That way the auth could be mocked and requests would be sent to that location instead of the staging api?~~ Due to the way that the api endpoints are configured in the frontend there is no way to really override the staging api endpoint setting with a different endpoint. The environment uses a 'frozen' object for just this reason that it is not able to be changed. Its good for security on production, but makes this idea not viable. 
  

### Background

After launching our most recent set of tasks we would like to cleanup the code to be reused, easier to read, and in a better organizational scheme. We churned through a lot of code quickly and would like to do some housekeeping.

### ACs
- [x] Tickets have been created/updated for additional work, specifically #92, #93, #98, and #99

**Comment by adamwhitlock1** [comment]
There is a PR draft that was created this morning here: https://github.com/department-of-veterans-affairs/vets-website/pull/31584 The good news is that it removes 730 lines of repeated code, but does have several merge conflicts that will now have to be resolved with the most recent version of main.

- all the pattern code is isolated into a folder for each pattern, but I also created a shared folder for things that are reused between patterns or tasks
- a second pattern has been started, and just has a placeholder component, but the plumbing is now available to wire up new pattern applications where needed

Next I will fill in more details for unit test ticket for any reusable components, and the refactoring ticket

**Comment by adamwhitlock1** [comment]
Updated the AC for each ticket to continue the work on this. I will review the draft PR with Belle as well and make suer we are in agreement on how future code organization should be structured.

**Comment by beckyphung** [comment]
Looks good to me, moving to closed
