### ISSUE TITLE
Reseach how to update name/dob/ssn and confirm our instructions are correct [CAIA design debt]

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#95]
CAIA reviewed our designs and asked about the text under the 'locked' view and if it gives accurate instructions on updating personal data offline. We need to research - how do those things really get updated? Is that information in the note accurate? 

As it applies to the pattern guidance, I think it will be important to provide accurate info around updating data that cant be updated online. While this task might technically be above and beyond/out of scope for our current pattern, I think it is still important to try and figure out if this information is correct or not so that we are sure our example guidance is accurate. 

### ACs
- [x] Research how to update:
    - [x] Name
    - [x] SSN
    - [x] DOB
    - [x] Gender
 - [x] Write up findings in a GitHub document
 - [x] Include in sprint demo

**Comment by msbtterswrth** [comment]
Asked Auth Exp team if they had any other information about updating un-updatable personal information in this [slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1725377955580589). If we find any important call outs I'll update this comment.

**Comment by msbtterswrth** [comment]
Danielle Thierry or Beth Potts may be able to help us answer this.

**Comment by beckyphung** [comment]
Sent a message in the CAIA channel [in this Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1725474201909539) for clarification on content.

**Comment by beckyphung** [comment]
Danielle will respond to these questions later today.

**Comment by ChristineRoseSteiffer** [comment]
I'm playing devil's advocate a bit here, but I wonder if, for the sake of thinking about this in the context of our overall pattern, we might not *need* these specific answers to move forward (once we confirm, at least, that the current guidance we're giving is generally correct)? Because the guidance around updating locked data seems like it should be different depending on the form itself (and might also depend what type of data is 'locked' on that specific form), I wonder if instead of providing a very prescriptive 'Note' in our pattern, we instead gave some general content guidelines for what the instructions should be for how to update the 'locked' data? We could include examples, like the ones we're seeing on these forms, but allow for variations across teams and datasets. Curious if @beckyphung or @msbtterswrth have any thoughts about this idea?

**Comment by msbtterswrth** [comment]
I really like that approach, i've seen guidance elsewhere for contextual alert content, I believe it was in the form team's content patterns folder that we could perhaps follow.

**Comment by ChristineRoseSteiffer** [comment]
Confirmed with Becky on our Monday call that this approach makes sense. Still waiting final confirmation from Danielle Thierry that this content is accurate. I think we can close this for now as we will continue to iterate on the specific guidelines around telling people how to update locked data fields in our next sprint. We have noted the inclusion of this guidance under the 'Prefill' section of the 'What is Prefill versus Update Prefill?' section of the Update Prefill Discovery document from ticket #58 from this sprint.
