### ISSUE TITLE
create task for build tests

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#99]
This task was broken out from #94 

### Background
As an engineer, I want to have automated tests so my merge requests will pass faster.

We should build tests around any new functionality or new components such as:
- navigation tabs
- landing page
- basic form flow e2e tests? (this might not be needed as they are very minimal flow and these forms are not shipping to production, but I think testing is not a bad idea, time permitting.)
- other tests

Acceptance Criteria
- [x] At least a single e2e test is created for each pattern task (green, yellow, purple)
- [x] At least one unit test is created for the navigation tabs
- [x] At least one unit test is created for the landing page
- [x] PR merged with main
- [ ] Review with team and PO

**Comment by adamwhitlock1** [comment]
Active branch is here:
https://github.com/department-of-veterans-affairs/vets-website/tree/AuthedPatterns/aw/99/prefill-tests

I've created 5 unit tests for the task tabs component.

Created 6ish e2e tests which covers the green, yellow, and purple tasks. 

Next up is work on unit tests for landing page component and then the work will be ready for PR.

**Comment by adamwhitlock1** [comment]
Created PR with e2e and unit tests added:

https://github.com/department-of-veterans-affairs/vets-website/pull/31799

Will follow up with Belle tomorrow. It's pushing our upper limit of 500 LOC for a PR but there are a couple cleanup items to address that will most likely spill into a secondary PR

**Comment by adamwhitlock1** [comment]
Merged in my tests PR after reviewing with Belle. This can be closed out now. Doesn't really have a really concrete way to "validate" other than running the tests locally on the main branch with the commands that I had documented in [the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31799)
